= Connecting Firebird to a Jmix Project

Firebird is not included in the list of DBMSs supported by Jmix out of the box. To connect an application to Firebird, use the https://github.com/makssent/jmix-firebird-addon[jmix-firebird^] add-on.

[IMPORTANT]
====
This section is intended primarily for migrating an existing Jmix application to Firebird. If you do not have an application yet or have no experience with Jmix, start with the xref:tutorial:index.adoc[tutorial]. You can use https://github.com/makssent/jmix-firebird-application[jmix-firebird-application^] as a foundation. It is a minimal Jmix project created from the standard template and already configured for Firebird.
====

The integration has been tested with the https://github.com/makssent/jmix-crm-firebird[jmix-crm-firebird^] application: the application ran with Firebird, Liquibase created the schema, the tests connected through Jaybird, and the project's core functionality worked. The entire xref:tutorial:index.adoc[tutorial] has also been tested with Firebird.

[IMPORTANT]
====
Add-on version `{addon-version}` supports only Jmix {latest-version}.
====

The following are required:

* a running Firebird server;
* an empty database, which must be created by Firebird before the application starts for the first time;
* a user account with permission to create and modify database objects.

[[configuration]]
== Connection Configuration

[[dependencies]]
[[datasource]]
=== Dependencies and application.properties

Add the add-on starter and the Jaybird driver to the `dependencies` block in the Jmix project's `build.gradle` file:

[source,groovy,subs="attributes+"]
----
dependencies {
    implementation '{addon-group}:jmix-firebird-starter:{addon-version}'
    runtimeOnly 'org.firebirdsql.jdbc:jaybird:{jaybird-version}'
}
----

If the project used the embedded HSQLDB database, remove the `runtimeOnly 'org.hsqldb:hsqldb'` dependency. After changing the file, refresh the Gradle project in the IDE.

In `src/main/resources/application.properties`, replace the default data source settings with those of the prepared Firebird database, then add the driver and DBMS type properties:

[source,properties]
----
main.datasource.url=jdbc:firebird://localhost:3050//path/to/application.fdb?encoding=UTF8
main.datasource.username=sysdba
main.datasource.password=your_password

# Added for Firebird
main.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver
jmix.data.dbms-type=firebird
----

In the JDBC URL, replace `/path/to/application.fdb` with the path to the Firebird database file, and replace `sysdba` and `your_password` with the database username and password.

Firebird is not included in the standard set of DBMS types that Jmix detects automatically. Therefore, the `jmix.data.dbms-type=firebird` property explicitly tells Jmix that the main data source uses Firebird. Based on this value, Jmix uses the Firebird implementations registered by the add-on.

See the https://github.com/makssent/jmix-crm-firebird/commit/48d1c6e2c58bdbdcf6eb9468c36f54f73f0eeedb[jmix-crm-firebird project commit^] for an example of adding the dependencies and configuring `application.properties`.

[[liquibase]]
=== Modifying Liquibase Changelogs

Add the add-on changelog include to `changelog.xml` and place it before the existing Jmix module and application changelog includes:

[source,xml]
----
<include file="/io/github/makssent/jmix/firebird/liquibase/changelog.xml"/>
----

The include order is important: the add-on changelog declares the Liquibase property values for Firebird that are used by the scripts included after it.

In Liquibase init files, replace the `UUID` type with the `${uuid.type}` property for every UUID column:

[source,xml]
----
<column name="ID" type="${uuid.type}">
----

The included add-on changelog defines the `uuid.type` property value for Firebird.

Add `firebird` to the `dbms` attributes in application changelogs:

[source,xml]
----
<insert tableName="USER_" dbms="postgresql, mssql, hsqldb, firebird">
----

See the https://github.com/makssent/jmix-crm-firebird/commit/213b0b3717eced383e9fefa3d0b5b4e2fcf22ff9[jmix-crm-firebird project commit^] for an example of Liquibase changes that add Firebird support.

The procedure for manually creating new changelogs is described in xref:liquibase-changelog.adoc[Creating a Liquibase Changelog].

Known integration limitations are listed in xref:limitations.adoc[Firebird Limitations]. A practical approach to adapting an existing application is demonstrated in xref:migration.adoc[Example of Migrating an Application to Firebird].
