= Firebird Limitations

This section summarizes known limitations and considerations for using Firebird with Jmix that were identified in practice. The points below were observed while running the real-world `jmix-crm` project on Firebird and completing the tutorial.

Although the `jmix-crm` tests run with Firebird revealed no additional limitations, other considerations or limitations may exist. They may not appear in the scenarios covered so far and may be discovered as Firebird is used further with Jmix.

[[changelog-generation]]
== Automatic Liquibase Changelog Generation

The main known limitation is that automatic Liquibase changelog generation does not work for Firebird. After changing the data model, you must create the required changesets manually.

Support for Firebird as a primary database was proposed directly for Jmix in https://github.com/jmix-framework/jmix/pull/5532[PR #5532^]. The Jmix team did not accept the PR because of the ongoing maintenance cost of supporting another DBMS and suggested implementing the support as an add-on.

As a result, Firebird support is implemented in the separate `jmix-firebird-addon` rather than in the main Jmix project. The add-on enables applications to work with Firebird, but automatic changelog generation for Firebird remains unavailable. Manually created changelogs are applied when the application starts.

[TIP]
====
For an example of creating a Liquibase changelog, see the xref:tutorial:data-in-ui.adoc#joining-date-attr[tutorial section on adding the joiningDate attribute]. It explains how to create a changelog with one changeset and describes the resulting changes.

The process of creating a Liquibase changelog is described in more detail in xref:liquibase-changelog.adoc[Creating a Liquibase Changelog].
====

[[third-party-support]]
== Firebird Support in Third-Party Libraries

Liquibase and EclipseLink already support Firebird. For example, EclipseLink provides a dedicated https://eclipse.dev/eclipselink/api/4.0/org.eclipse.persistence.core/org/eclipse/persistence/platform/database/FirebirdPlatform.html[Firebird platform^]. However, some of this support was originally developed for older Firebird versions. Checks and restrictions in third-party libraries do not always account for the capabilities of current DBMS versions.

This does not mean that all such limitations affect Jmix applications. However, if an incompatibility can be reproduced in Liquibase, EclipseLink, or another dependency, it should preferably be fixed in the corresponding upstream project rather than making a workaround a permanent part of `jmix-firebird-addon`.

[[sequence-start-value]]
=== Example: createSequence and startValue

When creating a sequence, Liquibase prohibited the `startValue` attribute for Firebird regardless of the database version. The following changeset:

[source,xml]
----
<createSequence sequenceName="CRM_PAYMENT_NUMBER" startValue="1000"/>
----

failed with the following error:

[source]
----
startValue is not allowed on firebird
----

This restriction is no longer applicable to Firebird 4.0 and later. To run the project, `jmix-crm-firebird` uses a temporary workaround: the regular changeset excludes Firebird, while a separate Firebird changeset creates the sequence without `startValue` and then sets the initial value with an SQL statement:

[source,xml]
----
<changeSet id="1" author="crm" dbms="!firebird">
    <createSequence sequenceName="CRM_PAYMENT_NUMBER" startValue="1000"/>
</changeSet>

<changeSet id="2" author="crm" dbms="firebird">
    <createSequence sequenceName="CRM_PAYMENT_NUMBER"/>
    <sql>ALTER SEQUENCE CRM_PAYMENT_NUMBER RESTART WITH 1000</sql>
</changeSet>
----

See the complete example in this https://github.com/makssent/jmix-crm-firebird/commit/724d0a46f18aa9188a7e847e03fedf2fb74456f9[jmix-crm-firebird commit^].

A fix was submitted directly to Liquibase: https://github.com/liquibase/liquibase/pull/7922[PR #7922^] makes support for `startValue` and `incrementBy` dependent on the Firebird version. The restrictions remain for versions earlier than 4.0 and are removed for Firebird 4.0 and later.

[[temporary-workarounds]]
== Temporary Workarounds

Until a fix is included in a release of the third-party library, a local workaround can be applied following the `jmix-crm-firebird` example. Such a solution should be considered temporary and added only for a confirmed incompatibility in the dependency version in use.

After upgrading to a version of Liquibase, EclipseLink, or another library that fixes the specific incompatibility with the Firebird version in use, remove the workaround. It is not a required architectural part of the Firebird integration with Jmix.
