= Creating a Liquibase Changelog

When working with Firebird, automatic Liquibase changelog generation by Jmix is unavailable. After changing the data model, you need to describe the corresponding schema change manually in a new changelog file. This limitation is discussed in more detail in xref:limitations.adoc#changelog-generation[Automatic Liquibase Changelog Generation].

This page describes how to create a changelog for a new schema change, using the addition of an attribute to an existing entity as an example.

[[create-file]]
== Creating a Changelog File

For each schema change, create a separate XML file in the application's changelog directory. The file name should indicate the execution order and purpose of the change. Use a numeric prefix and a brief description, for example:

[source,text]
----
060-add-user-joining-date.xml
----

In this name, `060` specifies the execution order, while `add-user-joining-date` describes the addition of the `joiningDate` attribute to the `User` entity. For the next change, select the next appropriate number and indicate its purpose in the file name.

[[schema-change]]
== Defining the Schema Change

First, determine which data model change must be reflected in the database and select the corresponding Liquibase change type. See the complete list in the https://docs.liquibase.com/oss/change-types[official Liquibase documentation^].

The following change types have already been used and verified in projects and examples with Jmix and Firebird:

[cols="1,2",options="header"]
|===
|Data model change
|Liquibase change type

|New entity
|`createTable`

|New attribute of an existing entity
|`addColumn`

|Reference to another entity
|`addColumn`, `createIndex`, and `addForeignKeyConstraint`

|New index
|`createIndex`

|New sequence
|`createSequence`
|===

Jmix runs the Liquibase version included in the application and does not restrict its set of change types. Therefore, Jmix should execute all change types available in that Liquibase version. The limitation on automatic changelog generation for Firebird does not affect the execution of manually created changelogs.

Liquibase support for Firebird has not been updated for a long time. Therefore, SQL generation or execution errors may occur on Firebird even for a change type declared as supported. A confirmed example of this limitation is described in xref:limitations.adoc#sequence-start-value[Example: createSequence and startValue].

[[changeset]]
== Defining a Changeset

Each changelog is an XML file with the `databaseChangeLog` root element. Define the schema change inside a `changeSet` element and specify its `id` and `author`.

The following changelog adds the `JOINING_DATE` column:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                      http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">

    <changeSet id="1" author="onboarding">
        <addColumn tableName="USER_">
            <column name="JOINING_DATE" type="date"/>
        </addColumn>
    </changeSet>

</databaseChangeLog>
----

In this example:

* `id="1"` and `author="onboarding"` identify the changeset;
* `addColumn` describes a change to an existing table;
* `tableName="USER_"` specifies the table of the `User` entity;
* `name="JOINING_DATE"` specifies the name of the new column;
* `type="date"` corresponds to an attribute of the Java `LocalDate` type;
* the `nullable="false"` constraint is not specified because the attribute is optional and existing rows must retain a `NULL` value.

For a complete example with a description of the changes, see the xref:tutorial:data-in-ui.adoc#joining-date-attr[tutorial section on adding the joiningDate attribute].

[[firebird-details]]
== Firebird-Specific Changelog Details

Most changes are described using standard Liquibase elements. Additional adaptation is required only when a changelog depends on the DBMS type or type mapping.

When creating a new table with UUID columns, specify the `${uuid.type}` property instead of a specific SQL type:

[source,xml]
----
<column name="ID" type="${uuid.type}">
    <constraints primaryKey="true" nullable="false"/>
</column>
----

The property value for Firebird is declared by the add-on changelog. An example of creating a table with a UUID identifier is provided in the xref:tutorial:simple-crud.adoc#run-app[tutorial section on creating the Step entity].

If an existing changeset is restricted by the `dbms` attribute and must run with Firebird, add `firebird` to the list:

[source,xml]
----
<insert tableName="USER_" dbms="postgresql, mssql, hsqldb, firebird">
----

The `dbms` attribute is not required for regular changes that must run on all supported DBMSs.

Operations limited by the Liquibase version in use may require a separate changeset with `dbms="firebird"`. A confirmed workaround for `createSequence` and `startValue` is described in xref:limitations.adoc#sequence-start-value[Example: createSequence and startValue].
